version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks: 
      - wordpress
    ports:
      - "8008:80"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on: 
      - php-fpm
    hostname: nginx
    container_name: wp-nginx

  php-fpm:
    build:
      dockerfile: Dockerfile
      context: ./php
    networks: 
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    hostname: php-fpm
    container_name: wp-php-fpm

  mysql:
    image: centos/mysql-56-centos7:latest
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql_db:/var/lib/mysql
    networks: 
      - wordpress
    hostname: mysql
    container_name: wp-mysql

volumes:
  wordpress:
  mysql_db:

networks:
  wordpress:

