version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v2.3.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
    hostname: prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox_exporter/config/:/etc/blackbox_exporter/
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - 9115:9115
    networks:
      - monitoring
    hostname: blackbox_exporter

  alertmanager:
    image: prom/alertmanager:v0.15.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - monitoring
    hostname: alertmanager

  grafana:
    image: grafana/grafana:5.2.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    hostname: grafana
    
volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
