version: '3'
service:

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks: 
      - sentry
    ports:
      - "8080:80"
    depends_on: 
      - sentry
    hostname: nginx
    container_name: sentry_nginx

  sentry:
    build:
      dockerfile: Dockerfile
      context: ./sentry
    networks:
      - sentry
    depens_on:
      - postgres
      - redis
    hostname: sentry
    container_name: sentry_sentry

  redis:
    image: redis
    restart: always
    networks: 
      - sentry
    hostname: redis
    container_name: sentry_redis

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
    networks: 
      - sentry
    volumes:
      - database:/var/lib/postgresql/data
    hostname: pgsql
    container_name: sentry_postgres

volumes:
  database:

networks:
  sentry:
