global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 1m

  external_labels:
    monitor: 'WebAcademy'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['2e.lab.int:9100']

  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://2e.lab.int:3000/
        - http://2e.lab.int:8081/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
